### ISSUE TITLE
Module not found: Can't resolve '@material-tailwind/react'

### ISSUE THREAD

**Issue by lkmSasanga** [creativetimofficial/material-tailwind#408] opened 2023-07-25 14:34 UTC
I have installed the package already but getting module not found. I'm using Nextjs 13.4.11

**Comment by abouhir** [comment] 2023-07-25 23:18
the same problem with me but with react project

**Comment by Rdrudra1999** [comment] 2023-07-26 06:25
Downgrade to "@material-tailwind/react": "^2.0.5", , it will solve your problem

**Comment by ComputerKeeda** [comment] 2023-07-26 07:47
@Rdrudra1999 you answer was correct bro but it was still showing the same error in my device so I tried this code

`"@material-tailwind/react": "2.0.5",`

and it worked 
thanks bro 😃

**Comment by sethumadh** [comment] 2023-07-28 00:15
Hi, The issue is still there.  I am using react vite , and none of the versions are working atm.

**Comment by mahatoHariom** [comment] 2023-07-28 09:41
> @Rdrudra1999 you answer was correct bro but it was still showing the same error in my device so I tried this code
> 
> `"@material-tailwind/react": "2.0.5",`
> 
> and it worked thanks bro 😃

IT worked and  "@material-tailwind/react": "2.0.6",` too  we just have to remove ^ from our version

**Comment by mahatoHariom** [comment] 2023-07-28 12:13
when will the material tailwind support react server component out of the box

**Comment by rohit-ojha-10** [comment] 2023-07-29 06:10
Downgrading to 2.0.5 worked , thank you so much!!!!

**Comment by rtmann** [comment] 2023-07-30 21:18
Still broken, confirmed downgrading works.

**Comment by sajadevo** [comment] 2023-07-31 08:59
Hey guys,

This issue is fixed on `v2.0.8`.

**Closed by sajadevo** 2023-07-31 08:59 UTC

**Comment by ComputerKeeda** [comment] 2024-04-22 12:32
> I'm at v2.1.9 and this problem exists for me.

try downgrading to version `v2.0.8`
