### ISSUE TITLE
labelProps not applying on label elements

### ISSUE THREAD

**Issue by lautaro-osacar** [creativetimofficial/material-tailwind#201] opened 2022-08-23 14:25 UTC
Hi! I'm trying to pass `labelProps` on an input in react package.
It seems that `labelProps` are not applying on any <label> element on the components.

see: https://github.com/creativetimofficial/material-tailwind/blob/1a8738335c41c0a2065a6025cda85875bcdd24ad/packages/material-tailwind-react/src/components/Input/index.tsx#L111

**Comment by sajadevo** [comment] 2022-09-05 10:31
Hi @lautaro-osacar,

The issue is fixed on v1.2.4 please update to the latest version for resolving this issue.

Cheers,
Sajad

**Closed by sajadevo** 2022-09-05 10:31 UTC
