### ISSUE TITLE
Tabs indicator props ignored on initial render

### ISSUE THREAD

**Issue by elwoodhouse** [creativetimofficial/material-tailwind#169] opened 2022-07-24 03:26 UTC
First off, thanks for making this library, I hope it continues to gain momentum.

I'm having this problem and I'm not sure if it's something I'm doing wrong or a bug.

When I setup a tabs header row and style the indicator with the indicator props, it renders as expected:

![image](https://user-images.githubusercontent.com/38488541/180629073-90c9c8b4-7696-4299-a72a-84bee713df74.png)

When I add the tabs body and add some panels, on the initial render the indicator props are ignored and it defaults to the white indicator:

![image](https://user-images.githubusercontent.com/38488541/180629137-df4c0e8c-e617-4b08-9299-54045b0f1a60.png)

After a re-render the indicator props are picked up and the component is styled as desired.

![image](https://user-images.githubusercontent.com/38488541/180629284-18b6d14f-b8db-43e1-8b81-fd8d3807ff25.png)

Is there something I need to set to get it working from initial render?

FYI, this module is loaded in an iframe if that makes any difference.

`const tabData: any = {
    Requests: { label: "Requests", panel: RequestsPanel },
    Faq: { label: "FAQ", panel: FaqPanel },
    DataSharingPrivacy: { label: "Data Sharing & Privacy", panel: DataSharingPrivacyPanel },
  };
  return (
    <div>
      <Tabs value="Requests" className="bg-ob_bg_blue">
        <TabsHeader className="rounded-none bg-inherit" indicatorProps={{ className: "!rounded-none !bg-ob_hl_blue" }}>
          {Object.keys(tabData).map((key: string) => (
            <Tab key={key} value={key} className="!text-white">
              {tabData[key]["label"]}
            </Tab>
          ))}
        </TabsHeader>
        <TabsBody>
          {Object.keys(tabData).map((key: string) => (
            <TabPanel key={key} value={key}>
              {React.createElement(tabData[key]["panel"], {})}
            </TabPanel>
          ))}
        </TabsBody>
      </Tabs>
    </div>
  );`

Thanks.

**Comment by sajadevo** [comment] 2022-07-25 06:31
Hi @elwoodhouse,

Could you please send me a link of the code you've done, you can use codesandbox or something similar to it for sharing the live code.

Cheers,
Sajad

**Comment by sajadevo** [comment] 2022-07-29 11:10
Hi @elwoodhouse,

The issue is fixed now please update your @material-tailwind/react project by running:
`npm i @material-tailwind/react@latest`.

Cheers,
Sajad

**Closed by sajadevo** 2022-07-29 11:10 UTC

**Comment by elwoodhouse** [comment] 2022-08-14 05:00
Sorry it took me so long to get back to this issue. Yes this is fixed now, thanks for fixing so promptly.
