### ISSUE TITLE
Overide ClassName for Modal Component 

### ISSUE THREAD

**Issue by reanyouda** [creativetimofficial/material-tailwind#65] opened 2021-08-02 07:44 UTC
Overide ClassName for Modal Component  not working at all?
any suggestion 

example :
```
 <Navbar color="lightBlue" className="flex flex-wrap items-center justify-between py-2.5 px-3 mb-0">
```

**Comment by oshimayoan** [comment] 2021-08-15 14:49
I believe this is a duplicate of #51

**Closed** 2022-05-12 18:25 UTC
