### ISSUE TITLE
Breakpoints not working with Material Tailwind & Next.js

### ISSUE THREAD

**Issue by dwalsh01** [creativetimofficial/material-tailwind#59] opened 2021-07-11 16:42 UTC
## Expected Behavior

After starting a fresh project with the next.js tailwindCSS starter template and installing the material-tailwind package as per the docs, I created a heading which I expect to be aligned to the left from medium screens and up. 

The code used is as follows:
```jsx
<h1 className="text-center text-3xl md:text-left">Hello</h1>
```

## Current Behavior

Instead I get the text centered at all screen sizes (breakpoints). This happens with multiple components within my fresh application. 

## Possible Solution

The only way I can get the application to work as intended is to remove the line importing the material tailwind CSS in the `_app.js` file and keep the `tailwindcss/tailwind.css` style import. 

My `_app.js` file is as follows:
```jsx
import Head from 'next/head';
import 'tailwindcss/tailwind.css';
// removing the below line makes the breakpoints work as intended
import '@material-tailwind/react/tailwind.css';

function MyApp({ Component, pageProps }) {
    return (
        <>
            <Head>
                <link
                    href="https://fonts.googleapis.com/icon?family=Material+Icons"
                    rel="stylesheet"
                />
            </Head>
            <Component {...pageProps} />
        </>
    );
}

export default MyApp;

```

## Steps to Reproduce (for bugs)

1. `npx create-next-app -e with-tailwindcss my-project`
2. `npm install -D tailwindcss@latest postcss@latest autoprefixer@latest`
3. `npx tailwindcss init -p`
4. `npm i -E @material-tailwind/react`
5. Import the material CSS file so your `_app.js` looks like so:
```jsx
import Head from 'next/head';
import 'tailwindcss/tailwind.css';
import '@material-tailwind/react/tailwind.css';

function MyApp({ Component, pageProps }) {
    return (
        <>
            <Head>
                <link
                    href="https://fonts.googleapis.com/icon?family=Material+Icons"
                    rel="stylesheet"
                />
            </Head>
            <Component {...pageProps} />
        </>
    );
}

export default MyApp;
```
6. In `index.js` create a component as follows:
```jsx

export default function Home() {
    return (
            <div>
                <h1 className="text-center text-3xl md:text-left">Hello</h1>
            </div>
    );
}
``` 
7. Once you view it in your browser and resize, you can see that text does not realign. 
8. 
## Context

I was watching a live coding session on YT and I saw the programmer run into this problem and not resolve it so I just had a quick look. 

## Your Environment

- Version used: ^0.3.4
- Browser Name and version:  Chrome version 91.0.4472.114 
- Operating System and version (desktop or mobile): Mac 
- Link to your project:

**Comment by DanDev95** [comment] 2021-07-27 13:29
Can confirm. This is incredibly annoying and ruins the entire library.

**Comment by kkd1215** [comment] 2021-08-16 13:10
Just created a couple of pages for a client's website.  After completing them, realized that the breakpoints didn't work because of the said CSS file. Please let me know if this has any solution.

**Comment by JorisHey** [comment] 2021-12-11 15:21
For what it's worth.

I had the same issue (though in my Gatsby project) and was able to fix this to first import Material-Tailwind and Tailwind itself after this import.

**Comment by levankhoabhc** [comment] 2022-01-05 01:14
I've just experienced this issues. The two CSS library probably not working together. I have to remove '@material-tailwind/react/tailwind.css' and trying to reproduce it somehow.

**Comment by diegoalvarezmgl** [comment] 2022-01-06 09:59
Same here, this is really annoying, I migrated my entire project from Create React App to NextJS and now nothing works because I cannot import this library, this is awful.

**Comment by sajadevo** [comment] 2022-05-12 18:31
Hi guys,

I've just updated @material-tailwind/react and this issue is fixed now.

All the best,
Sajad

**Closed by sajadevo** 2022-05-12 18:31 UTC
