### ISSUE TITLE
`Select` allows out-of-bounds index when `selected` is defined.

### ISSUE THREAD

**Issue by alexanderteno** [creativetimofficial/material-tailwind#415] opened 2023-08-02 02:55 UTC
Can be tested on docs example of a complex `<Select><Option/><Select>` scenario like that of Countries selection.

If you select either the top-most or bottom-most `<Option/>` you can then counter-navigate with the "up" or "down" keys into a negative index (empty `element`).

This seems unintentional, if you were to drop the `selected` prop from the example you will be able to find that counter-navigation from either the top or bottom correctly loops to the `0`th or `n`th element.

The attached video shows what I'm talking about. Except for my initial selection of "Kenya" all inputs are made on the keyboard ("up", "down", "return")

https://github.com/creativetimofficial/material-tailwind/assets/5354921/703abf5e-cf0a-4e29-938a-630e7f7b5fdf

**Comment by sajadevo** [comment] 2023-09-14 09:08
@alexanderteno  I've updated the example on the docs and the issue is fixed now.

**Closed by sajadevo** 2023-09-14 09:08 UTC

**Comment by alexanderteno** [comment] 2023-09-14 15:47
@sajadevo, Do you have a PR# that I can take a peek at?
