### ISSUE TITLE
tabs: Flash of unstyled content

### ISSUE THREAD

**Issue by DanielSmith** [creativetimofficial/material-tailwind#225] opened 2022-09-17 19:03 UTC
What is the recommended way to load tabs so that it does not flash like this?  I am using the example from the docs:

![CleanShot 2022-09-17 at 15 01 06](https://user-images.githubusercontent.com/167197/190872569-5e623761-17c9-4e4e-bffc-df3583d3cb43.gif)

**Comment by sajadevo** [comment] 2022-09-19 05:42
Hi @DanielSmith,

Which example you've used because on the docs as you can see we don't have any flashing.

Cheers,
Sajad

**Comment by sajadevo** [comment] 2022-12-04 20:29
Hey @DanielSmith,

I've tested the tabs and they're working find please update to the latest version of @material-tailwind/react maybe it cause by previous versions of the library.

Cheers,
Sajad

**Comment by blainehill2001** [comment] 2023-01-16 21:32
Hi,

I also have the same issue, but am running on version 1.2.5. 

It loads and shows the concatenation of all tabs for a split second. My tab code is taken straight from the documentation and am running on React 18.2.

See attached video:

https://user-images.githubusercontent.com/44901957/212768390-edd6d408-a9fe-456d-a9f6-15e90f36716a.mov

**Comment by boomspot** [comment] 2023-01-17 20:15
Same issue here with 1.25

**Comment by sajadevo** [comment] 2023-02-14 11:58
This issue has been fixed on v1.4.0.

**Closed by sajadevo** 2023-02-14 11:58 UTC
Labels: help wanted, fixed

**Comment by juanjlunar** [comment] 2023-03-07 22:41
It is still happening on v1.4.2

**Comment by sajadevo** [comment] 2023-03-09 05:38
@juanjlunar could you please share a short video or some code to reproduce the issue?

**Comment by juanjlunar** [comment] 2023-03-09 16:40
https://user-images.githubusercontent.com/26415034/224090732-5615b6b1-ffaa-4774-8d6f-f7f335170d9c.mov


Data to render:

```
const testData = [
  {
    id: 1,
    tab: 'tab-1',
    panelData: ['paragraph tab 1'],
  },
  {
    id: 2,
    tab: 'tab-2',
    panelData: ['paragraph tab 2'],
  },
  {
    id: 3,
    tab: 'tab-3',
    panelData: ['paragraph tab 3'],
  },
  {
    id: 4,
    tab: 'tab-4',
    panelData: ['paragraph tab 4'],
  },
]; 
```

Render tabs:
```
        <Tabs defaultValue={testData[0].id}>
          <TabsHeader>
            <div className="flex">
              {testData.map((testSingleData) => {
                return (
                  <Tab key={testSingleData.id} value={testSingleData.id}>
                    {testSingleData.tab}
                  </Tab>
                );
              })}
            </div>
          </TabsHeader>
          <TabsBody>
            {testData.map((testSingleData) => {
              return (
                <TabPanel
                  key={`panel-${testSingleData.id}`}
                  value={testSingleData.id}
                >
                  {testSingleData.panelData.map((p) => {
                    return <p>{p}</p>;
                  })}
                </TabPanel>
              );
            })}
          </TabsBody>
        </Tabs>
```
